"""
Test GPU Swing Points Against Actual Combo File Data
Compare our GPU swing detection with the swing points in the actual combo files
"""

import pandas as pd
import numpy as np
import sys
from pathlib import Path

# Add paths for imports
sys.path.append(str(Path(__file__).parent.parent / 'src'))

# GPU imports
from feature_engineering.unified_pipeline import UnifiedTechnicalIndicatorsPipeline

class ActualComboSwingTest:
    """
    Test GPU swing points against actual combo file data
    """
    
    def __init__(self):
        self.legacy_data_path = "/mnt/c/Users/krajcovic/Documents/Testing Data/backtest_data/dem07_25_tr_ba_data.parquet"
        self.combo_data_path = "/mnt/c/Users/krajcovic/Documents/Testing Data/ATS_3_data/data/combo_000.parquet"
        self.metadata_path = "/mnt/c/Users/krajcovic/Documents/Testing Data/ATS_3_data/combinations_metadata.parquet"
        
    def load_actual_combo_data(self):
        """Load the actual combo file that was generated by legacy code"""
        print("📊 Loading actual combo file data...")
        
        combo_data = pd.read_parquet(self.combo_data_path)
        metadata = pd.read_parquet(self.metadata_path)
        combo_0_params = metadata[metadata['combo_id'] == 0].iloc[0]
        
        print(f"✅ Loaded actual combo data: {combo_data.shape}")
        print(f"   Columns: {list(combo_data.columns)}")
        print(f"   Parameters: MACD({combo_0_params['macd_short']},{combo_0_params['macd_long']},{combo_0_params['macd_signal']}), ATR({combo_0_params['atr_lookback']})")
        
        # Check if combo data has swing points
        swing_cols = [col for col in combo_data.columns if 'swing' in col.lower()]
        print(f"   Swing-related columns: {swing_cols}")
        
        return combo_data, combo_0_params
        
    def generate_gpu_swing_points(self, combo_params):
        """Generate swing points using our GPU pipeline with identical candle generation"""
        print("🚀 Generating GPU swing points...")
        
        # Load tick data
        tick_data = pd.read_parquet(self.legacy_data_path)
        print(f"✅ Loaded {len(tick_data):,} tick records")
        
        # Convert tick data to legacy candle format (same as combo generation)
        period_data = tick_data.reset_index()
        period_data.rename(columns={period_data.columns[0]: 'datetime'}, inplace=True)
        
        # Add required columns
        if 'tradeid' not in period_data.columns:
            period_data['tradeid'] = 'T' + period_data.index.astype(str)
        if 'nanotime' not in period_data.columns:
            period_data['nanotime'] = period_data.index
            
        # Set datetime as index (legacy method)
        if 'datetime' in period_data.columns:
            period_data['datetime'] = pd.to_datetime(period_data['datetime'])
            period_data = period_data.set_index('datetime')
        
        # EXACT legacy candle aggregation
        candles = period_data.groupby(pd.Grouper(freq='15T')).agg({
            'price': ['first', 'max', 'min', 'last', 'count'],
            'tradeid': 'first',
            'nanotime': 'first'
        }).dropna()
        
        # Flatten column names
        candles.columns = ['open', 'high', 'low', 'close', 'volume', 'tradeid', 'nanotime']
        
        print(f"✅ Generated candles: {candles.shape}")
        
        # Set up GPU pipeline
        pipeline = UnifiedTechnicalIndicatorsPipeline(dtype='float32')
        
        # Extract parameters
        macd_params = {
            'fast': int(combo_params['macd_short']),
            'slow': int(combo_params['macd_long']),
            'signal': int(combo_params['macd_signal'])
        }
        atr_lookback = int(combo_params['atr_lookback'])
        
        # Prepare candle data for GPU
        gpu_candles = candles[['open', 'high', 'low', 'close', 'volume']].copy()
        
        # Process with GPU pipeline
        print("🚀 Computing GPU indicators...")
        gpu_result = pipeline.compute_all_indicators(
            data=gpu_candles,
            macd_params=macd_params,
            atr_period=atr_lookback
        )
        
        print(f"✅ GPU processing complete: {gpu_result.shape}")
        print(f"   GPU columns: {list(gpu_result.columns)}")
        
        return gpu_result
        
    def compare_swing_points(self, combo_data, gpu_data, tolerance=1e-4):
        """Compare swing points between actual combo data and GPU results"""
        print("🔍 Comparing Swing Points...")
        print("=" * 60)
        
        # Check what swing-related data exists in combo file
        combo_swing_cols = [col for col in combo_data.columns if 'swing' in col.lower()]
        gpu_swing_cols = [col for col in gpu_data.columns if 'swing' in col.lower()]
        
        print(f"📊 Combo file swing columns: {combo_swing_cols}")
        print(f"📊 GPU swing columns: {gpu_swing_cols}")
        
        if not combo_swing_cols:
            print("❌ No swing point data found in combo file!")
            print("   The combo file might not contain swing point calculations")
            return None
            
        if not gpu_swing_cols:
            print("❌ No swing point data found in GPU results!")
            return None
        
        # Align data lengths
        min_len = min(len(combo_data), len(gpu_data))
        combo_subset = combo_data.iloc[:min_len].reset_index(drop=True)
        gpu_subset = gpu_data.iloc[:min_len].reset_index(drop=True)
        
        print(f"📊 Comparing {min_len} records")
        
        results = {}
        
        # Try to match swing columns
        combo_swing_map = {
            'swing_high': 'swing_highs',
            'swing_low': 'swing_lows',
            'swing_highs': 'swing_highs',
            'swing_lows': 'swing_lows'
        }
        
        for combo_col in combo_swing_cols:
            # Try to find matching GPU column
            gpu_col = None
            for combo_key, gpu_key in combo_swing_map.items():
                if combo_key in combo_col.lower() and gpu_key in gpu_swing_cols:
                    gpu_col = gpu_key
                    break
            
            if not gpu_col:
                print(f"⚠️  No matching GPU column found for {combo_col}")
                continue
                
            # Get non-null values for comparison
            combo_values = combo_subset[combo_col].dropna()
            gpu_values = gpu_subset[gpu_col].dropna()
            
            print(f"\n🔍 Comparing {combo_col} vs {gpu_col}:")
            print(f"   Combo non-null values: {len(combo_values)}")
            print(f"   GPU non-null values: {len(gpu_values)}")
            
            if len(combo_values) == 0 or len(gpu_values) == 0:
                print(f"   ⚠️  No valid values for comparison")
                continue
            
            # Show sample values
            print(f"   Sample combo values: {combo_values.head(5).values}")
            print(f"   Sample GPU values: {gpu_values.head(5).values}")
            
            # Check if GPU swing points are boolean flags vs actual price values
            gpu_unique = gpu_values.unique()
            combo_unique = combo_values.unique()
            
            print(f"   Combo value range: {combo_values.min():.2f} to {combo_values.max():.2f}")
            print(f"   GPU value range: {gpu_values.min():.2f} to {gpu_values.max():.2f}")
            print(f"   GPU unique values: {len(gpu_unique)} unique values")
            print(f"   Combo unique values: {len(combo_unique)} unique values")
            
            # Check if GPU values are boolean/binary vs continuous price values
            is_gpu_binary = len(gpu_unique) <= 2 and set(gpu_unique).issubset({0, 1, True, False})
            is_combo_continuous = len(combo_unique) > 10 and combo_values.min() > 10  # Assume prices > 10
            
            if is_gpu_binary and is_combo_continuous:
                print(f"   🔍 GPU data appears to be boolean flags (swing detection)")
                print(f"   🔍 Combo data appears to be actual price levels")
                print(f"   ❌ Cannot directly compare boolean flags vs price levels")
                
                # Count number of swing points detected
                gpu_swing_count = gpu_values.sum() if gpu_values.dtype == bool else (gpu_values == 1).sum()
                print(f"   📊 GPU detected {gpu_swing_count} swing points")
                
            else:
                print(f"   🔍 Both appear to be price-level data - attempting comparison")
                
                # Align by taking minimum length
                compare_len = min(len(combo_values), len(gpu_values))
                combo_compare = combo_values.iloc[:compare_len]
                gpu_compare = gpu_values.iloc[:compare_len]
                
                # Calculate differences
                abs_diff = np.abs(combo_compare - gpu_compare)
                max_diff = abs_diff.max()
                mean_diff = abs_diff.mean()
                
                # Check if values match within tolerance
                matches = abs_diff <= tolerance
                match_rate = matches.sum() / len(matches) * 100
                
                status = "✅ MATCH" if match_rate >= 95.0 else "❌ MISMATCH"
                print(f"   {status} Match rate: {match_rate:.1f}%")
                print(f"   Max difference: {max_diff:.2e}")
                print(f"   Mean difference: {mean_diff:.2e}")
                
                results[combo_col] = {
                    'gpu_col': gpu_col,
                    'max_diff': max_diff,
                    'mean_diff': mean_diff,
                    'match_rate': match_rate,
                    'compared_values': compare_len,
                    'matches_tolerance': match_rate >= 95.0
                }
        
        return results
        
    def analyze_combo_file_structure(self, combo_data):
        """Analyze the structure and content of the combo file"""
        print("🔍 Analyzing Combo File Structure...")
        print("=" * 60)
        
        print(f"📊 Shape: {combo_data.shape}")
        print(f"📊 Columns: {list(combo_data.columns)}")
        print(f"📊 Data types:\n{combo_data.dtypes}")
        
        # Look for any swing-related calculations
        swing_cols = [col for col in combo_data.columns if 'swing' in col.lower()]
        if swing_cols:
            print(f"\n📈 Swing-related columns found: {swing_cols}")
            for col in swing_cols:
                values = combo_data[col].dropna()
                if len(values) > 0:
                    print(f"   {col}: {len(values)} non-null values")
                    print(f"      Range: {values.min():.6f} to {values.max():.6f}")
                    print(f"      Sample: {values.head(3).values}")
        else:
            print("\n❌ No swing-related columns found in combo file")
            
        # Look for any intermediate calculations
        calc_cols = [col for col in combo_data.columns if any(keyword in col.lower() for keyword in ['range', 'position', 'high', 'low'])]
        if calc_cols:
            print(f"\n📊 Calculation-related columns: {calc_cols}")
            
        # Show sample data
        print(f"\n📋 Sample data (first 3 rows):")
        print(combo_data.head(3))
        
    def run_test(self):
        """Run the complete test"""
        print("🔬 ACTUAL COMBO SWING POINT TEST")
        print("=" * 80)
        print("Testing if our GPU swing points match the actual combo file data")
        print()
        
        # Load actual combo data
        combo_data, combo_params = self.load_actual_combo_data()
        
        # Analyze combo file structure
        print("\n" + "="*60)
        self.analyze_combo_file_structure(combo_data)
        
        # Generate GPU swing points
        print("\n" + "="*60)
        gpu_data = self.generate_gpu_swing_points(combo_params)
        
        # Compare swing points
        print("\n" + "="*60)
        comparison_results = self.compare_swing_points(combo_data, gpu_data)
        
        # Summary
        print(f"\n📈 TEST SUMMARY:")
        print("=" * 40)
        
        if comparison_results:
            total_comparisons = len(comparison_results)
            successful_matches = sum(1 for r in comparison_results.values() if r.get('matches_tolerance', False))
            
            print(f"   Total swing comparisons: {total_comparisons}")
            print(f"   Successful matches: {successful_matches}")
            print(f"   Overall success rate: {successful_matches/total_comparisons*100:.1f}%") if total_comparisons > 0 else print("   No successful comparisons")
            
            if successful_matches == total_comparisons and total_comparisons > 0:
                print(f"\n🎉 SUCCESS! GPU swing points match actual combo file")
                print(f"✅ All {total_comparisons} swing calculations aligned")
            else:
                print(f"\n⚠️  PARTIAL/NO MATCH: {successful_matches}/{total_comparisons} swing calculations match")
        else:
            print("   No swing point comparisons could be made")
            print("   This indicates the combo file uses different swing calculation methods")
            
        return comparison_results

def main():
    """Main test function"""
    print("🚀 Starting Actual Combo Swing Point Test")
    print("=" * 80)
    
    test = ActualComboSwingTest()
    
    # Run the test
    results = test.run_test()
    
    print(f"\n🎊 TEST COMPLETE!")
    
    if results:
        print("\n📋 DETAILED RESULTS:")
        for swing_col, result in results.items():
            status = "✅" if result.get('matches_tolerance', False) else "❌"
            match_rate = result.get('match_rate', 0)
            print(f"   {status} {swing_col}: {match_rate:.1f}% match rate")
    else:
        print("\n🔍 No swing point comparisons possible")
        print("   The actual combo files likely use completely different swing calculations")
        print("   or store swing data in a different format than expected")

if __name__ == "__main__":
    main()