[autotrader]
autotrader_user = AT_USER

[loggers]
keys=root,autotrader

[logger_root]
level=ERROR
handlers=file_root

[logger_autotrader]
qualname=autotrader
level=DEBUG
handlers=file_autotrader

[formatters]
keys=plain

[formatter_plain]
format=%(asctime)s.%(msecs)03d %(levelname)s [%(name)s] %(message)s
datefmt=%Y-%m-%d %H:%M:%S

[handlers]
keys=stream,file_autotrader, file_root

[handler_stream]
class=StreamHandler
formatter=plain
args=()

[handler_file_autotrader]
class=logging.handlers.TimedRotatingFileHandler
formatter=plain
args=('epex-autotrader.log', 'H', 2, 60)

[handler_file_root]
class=logging.NullHandler
formatter=plain
args=()
