from __future__ import absolute_import
import collections
import datetime
import functools
import json
import math
import re
import time
import six

import autotrader_lib.common as COMMON
import autotrader_core.persistence as PERSIST
import autotrader_lib.util as ALU
if six.PY2:
    import autotrader_lib.fast_logging_py2 as FLOG
else:
    import autotrader_lib.fast_logging_py3 as FLOG
from six.moves import range

log = FLOG.getLogger("autotrader.exchange_rate_limiting")


def ts_to_isoformat(ts):  # type: (float|int|None) -> str|None
    """Convert timestamp to iso formatted datetime string"""
    return datetime.datetime.utcfromtimestamp(float(ts)).isoformat() if ts is not None else None


class RateLimitManager(object):
    """Generic class for exchange rate limit managers."""

    def __init__(self, parameters, bucket_length):  # type: (ALU.ActionRateParameters, int) -> None
        """Creates a new RateLimitManager object
        :param parameters: the Action Rate parameters object used for storing rate limiting information
        :param bucket_length: the length of the buckets for the rolling time in seconds
        """
        self.parameters = parameters
        self._buckets = collections.defaultdict(int)
        self._bucket_length = bucket_length

    def _decay_buckets(self, current_time):  # type: (float) -> None
        """Checks and deletes invalid buckets."""
        for key in list(self._buckets.keys()):
            if key < self._oldest_bucket(current_time):
                log.debug("Deleting %s limit bucket {'%s': %s}; last: %s", self.parameters.limit_type,
                          ts_to_isoformat(key), self._buckets[key], ts_to_isoformat(self._oldest_bucket(current_time)))
                del self._buckets[key]

    def _current_bucket(self, current_time):  # type: (float) -> int
        """Calculates the start timestamp of the current bucket."""
        return self._get_bucket(current_time)

    def _get_bucket(self, ts):  # type: (float) -> int
        """Calculates the bucket for the given timestamp

        :param ts: timestamp to calculate the bucket-ts for
        :return: bucket key for the timestamp
        """
        return int(math.floor(ts / self._bucket_length) * self._bucket_length)

    def _oldest_bucket(self, current_time):  # type: (float) -> None
        """Calculates the last valid bucket timestamp."""
        raise NotImplementedError()

    def from_dict(self, data):  # type: (dict[str, any]) -> None
        """Updates itself from a dict.

        :param data: data dict generated by RateLimitManager.to_dict
        """
        self.parameters.from_dict(data)
        if isinstance(data.get("_buckets"), dict):
            self._buckets = collections.defaultdict(int, {
                int(key): val for key, val in data["_buckets"].items()
            })

    def to_dict(self, with_buckets=False):
        """Generates a dict from itself.

        :param with_buckets: Should the buckets also be included, defaults to False
        :type with_buckets: bool, optional
        :return: dict of this object, can be used in RateLimitManager.from_json
        :rtype: dict
        """
        data = self.parameters.to_dict()
        if with_buckets:
            data["_buckets"] = {str(k): v for k, v in self._buckets.items()}
        return data

    def increment(self, current_time, n=1):  # type: (float, int) -> None
        """ Increments the current bucket by the given amount. Only call this in the parent.

        :param n: amount to increment, defaults to 1
        """
        bucket_ts = self._current_bucket(current_time)
        self._buckets[bucket_ts] += n

    def calculate_current(self, current_time):  # type: (float) -> int
        """Calculate the current rate value. Removes invalid buckets before calculation."""
        self._decay_buckets(current_time)
        return sum(self._buckets.values())


class StateMachine(object):
    """Keeps track of states and stores a history. Detects state changes and fetch specific handlers to that state"""

    def __init__(self, label, ordered_possible_states, max_elements=10, change_handlers=None):
        # type: (str, list[str], int, dict[str, any]) -> None
        """Creates a new StateMachine object

        :param label: name of this StateMachine object, is used for logs
        :param ordered_possible_states: Ordered list of possible states (first element is least severe)
        :param max_elements: max amount of state changes to store in history, defaults to 10
        :param change_handlers: dict of handler functions with the state as key, defaults to None
        """
        self.label = label
        self.ordered_possible_states = ordered_possible_states
        self._max_len = max_elements

        self._severity_dict = collections.defaultdict(
            int,
            {ordered_possible_states[index]: index for index in range(len(ordered_possible_states))}
        )
        self.state_event_handler_map = change_handlers or {}
        self.history = collections.deque()  # type: collections.deque[tuple[str|None, float|None]]

    @property
    def severity(self):  # type: () -> int
        """Numerical severity of the current state, so it can be compared."""
        return self._severity_dict[self.current]

    def _get_element(self, index=0):  # type: (int) -> tuple[str|None, float|None]
        """Get a specific element from the history. If not available the result will be (None, None)."""
        return self.history[index] if len(self.history) > index else (None, None)

    @property
    def current(self):  # type: () -> str|None
        """Retrieves the current state"""
        return self._get_element()[0]

    @property
    def previous(self):  # type: () -> str|None
        """Retrieves the previous state"""
        return self._get_element(1)[0]

    @property
    def last_changed(self):  # type: () -> float|None
        """Retrieves the timestamp when the current state was set."""
        return self._get_element()[1]

    @staticmethod
    def empty_event_handler(*_, **__):  # type: (list, dict) -> None
        """Empty event handler. This will be used if the state didn't have a specified event handler"""
        return None

    def register(self, new_state, current_timestamp):  # type: (str, float) -> bool|any
        """Registers a state. If the state is new it will be inserted in the history and the handler for that state will
        be returned.
        If the history is empty, any state will be inserted in the history, but it will not count as changed.
        """
        if new_state == self.current:  # State dind't change
            return False
        is_escalading = self.severity < self._severity_dict[new_state]

        self.history.appendleft((new_state, current_timestamp))
        if len(self.history) > self._max_len:
            self.history.pop()

        if self.previous is None:  # Previous state was None -> doesn't count as changed
            return False
        handler = self.state_event_handler_map.get(new_state) or StateMachine.empty_event_handler
        return functools.partial(handler, is_escalading=is_escalading)

    def load_data(self, data):  # type: (list[list[str|float|None]]) -> None
        """Loads the data object into the history while prioritizing newer elements."""
        can_load = self._max_len - len(self.history)
        converted = [(el[0], el[1]) for el in data[:can_load]]
        self.history.extend(converted)

    def data(self):  # type: () -> list
        """Returns a data object that can be persisted."""
        return list(self.history)


def only_initialized(default=None):
    def decorator(func):
        def wrapper(omt, *args, **kwargs):  # type: (OMTManager, list, dict) -> any
            if not omt.initialized:
                return default
            return func(omt, *args, **kwargs)
        return wrapper
    return decorator


class OMTManager(RateLimitManager):
    parameters = None  # type: ALU.OMTParameters
    _state_regex = r"({})\D*(\d+-\d+-\d+T\d+:\d+:\d+)?".format(
        "|".join([val for key, val in COMMON.EpexOMTState.__dict__.items() if not key.startswith("_")])
    )

    OBSERVATION_PERIOD_BUCKET_SIZE = {
        COMMON.RateLimitType.Epex.short: 1,
        COMMON.RateLimitType.Epex.long: COMMON.QUARTER,
    }

    def __init__(self, limit_type, throttling_limit, change_handlers=None):  # type: (str, int, dict[str, any]) -> None
        """Creates a new OMTManager object

        :param limit_type: the type of OMTManager (short or long)
        :param throttling_limit: the percentage of the upper threshold until which we are allowed to trade.
        :param change_handlers: dict of change handler fucntions with the state as key, defaults to None
        """
        super(OMTManager, self).__init__(ALU.OMTParameters(limit_type=limit_type, exchange_difference=0),
                                         self.OBSERVATION_PERIOD_BUCKET_SIZE[limit_type])
        if throttling_limit < 0:
            log.warning("The configured {}_throttling_limit is too low ({}% < 0%), using 0%."
                        "".format(limit_type, throttling_limit))
            throttling_limit = 0
        elif throttling_limit > 100:
            log.warning("The configured {}_throttling_limit is too high ({}% > 100%), using 100%."
                        "".format(limit_type, throttling_limit))
            throttling_limit = 100

        self.throttling_limit_ratio = throttling_limit
        self.epex_state = StateMachine("EPEX", [
            COMMON.EpexOMTState.NO_RESTRICTION, COMMON.EpexOMTState.WARNING, COMMON.EpexOMTState.RESTRICTED],
            change_handlers=change_handlers,
        )
        self.autotrader_state = StateMachine("AutoTrader", [
            COMMON.ThrottlingState.NON_BLOCKING, COMMON.ThrottlingState.BLOCKING],
            change_handlers=change_handlers,
        )

    @property
    def initialized(self):  # type: () -> bool
        """Wether aT received the first omt status response from EPEX (so we don't do calculations with None values)"""
        return None not in [self.parameters.lower_threshold, self.parameters.upper_threshold,
                            self.parameters.observation_period, self.parameters.cooldown_period,
                            self.parameters.tolerance_period, self.parameters.received_omt]

    @property
    def _raw_throttling_threshold(self):
        """The raw throttling threshold calculated by multiplying the config with L2.
        Should not be used for throttling."""
        if not self.initialized:
            return None
        return int(self.parameters.upper_threshold * self.throttling_limit_ratio / 100)

    @property
    def throttling_threshold(self):
        """The effective throttling threshold where L1 is the floor. Should be used for throttling."""
        if not self.initialized:
            return None
        return max(self.parameters.lower_threshold, self._raw_throttling_threshold)

    def increment(self, current_time, n=1):  # type: (float, int) -> None
        """ Increments the current bucket by the given amount. Only call this in the parent.

        :param n: amount to increment, defaults to 1
        """
        super(OMTManager, self).increment(current_time, n)
        self.update_current_omt(current_time)

    def update_current_omt(self, current_time, from_db=False):  # type: (float, bool) -> None
        """Updates the current OMT value"""
        self.parameters._calculated_omt = max(
            self.calculate_current(current_time) + self.parameters.exchange_difference, 0
        )
        self._evaluate_epex_state(current_time, from_db=from_db)

    def _oldest_bucket(self, current_time):  # type: (float) -> int
        """Calculates the last valid bucket timestamp."""
        observation_period = (
            current_time if self.parameters.observation_period is None
            else self.parameters.observation_period - self._bucket_length
        )
        return self._get_bucket(current_time - observation_period)

    def from_dict(self, data, current_time=None):  # type: (dict[str, any], float|None) -> OMTManager
        """Updates itself with data from the dict."""
        current_time = current_time if current_time else time.time()
        from_exchange = data.get("from_exchange", False)
        if not from_exchange:
            self.autotrader_state.load_data(data.get("throttling_state_history", []))
            self.epex_state.load_data(data.get("epex_state_history", []))

        old_received_omt = self.parameters.received_omt
        old_lower_threshold = self.parameters.lower_threshold
        old_upper_threshold = self.parameters.upper_threshold
        super(OMTManager, self).from_dict(data)

        new_received_omt = data.get("received_omt")
        if new_received_omt != old_received_omt:
            self.parameters.exchange_difference = self._determine_exchange_omt_difference(current_time, from_exchange)

        if ((old_lower_threshold != self.parameters.lower_threshold
             or old_upper_threshold != self.parameters.upper_threshold)
                and self._raw_throttling_threshold < self.parameters.lower_threshold):
            log.warning("The effective configured {}_throttling_limit of {}% is lower than L1 ({} < {}), using {}."
                        "".format(self.parameters.limit_type, self.throttling_limit_ratio,
                                  self._raw_throttling_threshold, self.parameters.lower_threshold,
                                  self.throttling_threshold))

        self.parameters.throttling_threshold = self.throttling_threshold
        self._update_recovery_omt_target()
        self.update_current_omt(current_time, not from_exchange)
        return self

    def to_dict(self, with_buckets=False):  # type: (bool) -> dict[str, any]
        """Generates a json object that can be transferred or persisted."""
        data = super(OMTManager, self).to_dict(with_buckets)
        data["throttling_state_history"] = self.autotrader_state.data()
        data["epex_state_history"] = self.epex_state.data()
        return data

    def to_json(self, with_buckets=False):  # type: (bool) -> str
        """Generates a json string for logging"""
        timestamp_keys = ("cooldown_end_ts", "tolerance_end_ts", "epex_status_since", "throttling_status_since")
        data = self.to_dict(with_buckets)
        for key in timestamp_keys:
            data[key] = ts_to_isoformat(data[key]) if data[key] is not None else None

        if with_buckets:
            data["_buckets"] = {ts_to_isoformat(k): data["_buckets"][k] for k in data["_buckets"]}

        data["throttling_state_history"] = [
            (state, ts_to_isoformat(ts)) for (state, ts) in data["throttling_state_history"]
        ]
        data["epex_state_history"] = [(state, ts_to_isoformat(ts)) for (state, ts) in data["epex_state_history"]]
        return json.dumps(data, default=str)

    @only_initialized(default=0)
    def _determine_exchange_omt_difference(self, current_time, from_exchange=True):  # (float, bool) -> int
        """Returns the difference if the locally calculated omt is lower than received from the exchange.

        In case this calculation was not triggered by a message from the exchange, return the previous value.
        :param from_exchange: True if the calculation was triggered by a message from the exchange, False otherwise
        :return: Difference of received to calculated OMT
        """
        if not from_exchange:
            # Don't recalculate exchange_difference on loading db object -> necessary for readonly simulation
            return self.parameters.exchange_difference or 0

        difference = self.parameters.received_omt - self.calculate_current(current_time)
        if difference > 0:
            log.debug("%s OMT from exchange is larger. Difference: %s", self.parameters.limit_type, difference)
        return difference

    @staticmethod
    def parse_status_update(state_str, fallback):  # type: (str|None, str) -> tuple[str, float|None]
        """Parse the information string from the throttling status changed messages.
        Extracts the status and timestamp of tolerance or cooldown end."""
        if state_str is None:
            return fallback, None

        # possible state_str values:
        #  - "NO_RESTRICTION"
        #  - "status=NO_RESTRICTION"
        #  - "status=WARNING, end of tolerance:2022-08-18T15:08:07+02:00"
        #  - "status=RESTRICTED, release time:2022-08-18T15:07:27+02:00"
        match = re.search(OMTManager._state_regex, state_str)

        if match is None:
            log.warning("Couldn't parse throttling state changed message \"{}\", using fallback state instead: {}"
                        "".format(state_str, fallback))
            return fallback, None

        state = match.group(1)
        date_str = match.group(2)

        timestamp = None
        if date_str:
            dt = ALU.convert_string_to_dt(date_str, "%Y-%m-%dT%H:%M:%S")
            timestamp = time.mktime(dt.timetuple())

        return state, timestamp

    @only_initialized()
    def _get_autotrader_state(self, current_time):  # type: (float) -> str|None
        """Evaluates the current state of OMT and returns the current state-string"""
        current_state = self.autotrader_state.current

        if(
                self.parameters.current_level >= self.throttling_threshold
                or (self.parameters.cooldown_end_ts is not None and current_time < self.parameters.cooldown_end_ts)
                or self.epex_state.current == COMMON.EpexOMTState.RESTRICTED
        ):
            return COMMON.ThrottlingState.BLOCKING
        elif self.parameters.recovery_target is not None and \
                self.parameters.current_level > self.parameters.recovery_target and current_state is not None:
            return current_state  # if omt is over the target recovery omt, take previous state
        else:
            return COMMON.ThrottlingState.NON_BLOCKING

    def _evaluate_autotrader_state(self, current_time, from_db=False):  # type: (float, bool) -> None
        """Checks if the autotrader throttling state has changed and runs change handlers

        :param from_db: whether the state was loaded from the database, don't run handlers if True, defaults to False
        """
        current_state = self._get_autotrader_state(current_time) or self.autotrader_state.current
        state_changed_handler = self.autotrader_state.register(current_state, current_time)
        self.parameters.throttling_status = self.autotrader_state.current
        self.parameters.throttling_status_since = self.autotrader_state.last_changed

        if state_changed_handler and not from_db:
            self._state_changed(self.autotrader_state, state_changed_handler)

    def _evaluate_epex_state(self, current_time, new_state=None, from_db=False, omt_timestamp=None):
        # type: (float, bool, str, float) -> None
        """Check if the epex status has changed and call the corresponding change handlers

        :param new_state: new state from epex, only necessary for the state
        :param from_db: whether the state was loaded from the database, don't run handlers if True, defaults to False
        :param omt_timestamp: end timestamp from state update message. If None don't update end-timestamps
        """
        if new_state:
            self.parameters.status = new_state

        state_changed_handler = self.epex_state.register(self.parameters.status, current_time)
        self.parameters.epex_status_since = self.epex_state.last_changed
        # update autotrader state according to epex state (before handlers are called)
        self._evaluate_autotrader_state(current_time, from_db=from_db)

        if state_changed_handler or omt_timestamp is not None:
            # in case the state change message comes later from the exchange this has to be checked separately
            self._update_end_ts(current_time, omt_timestamp)

        if state_changed_handler and not from_db:  # don't run handler when loading omt from mongo
            self._state_changed(self.epex_state, state_changed_handler)

    def _state_changed(self, state, handler):  # type: (StateMachine, any) -> None
        """Logs state changes, updates the database and calls the state change handlers."""
        log.debug("{} {} OMT state changed {}->{}"
                  "".format(self.parameters.limit_type, state.label, state.previous, state.current))
        PERSIST.MongoDBConnector().update_db_rate_limit(self.to_dict(True), COMMON.Exchange.epex)
        handler(omt=self)  # handler is first called here, so restart still triggers the log and persistence

    @only_initialized()
    def _update_end_ts(self, current_time, omt_timestamp):  # type: (float, float|None) -> None
        """Update the tolerance_end_ts and cooldown_end_ts of the OMTParameters object

        :param omt_timestamp: end timestamp from state update message. If None calculate using current_time
        """

        cooldown_ts = tolerance_ts = omt_timestamp
        if omt_timestamp is None:  # calculate cooldown and tolerance end if triggered by autotrader
            cooldown_ts = current_time + self.parameters.cooldown_period
            tolerance_ts = current_time + self.parameters.tolerance_period

        state = self.parameters.status
        self.parameters.tolerance_end_ts = tolerance_ts if state == COMMON.EpexOMTState.WARNING else None
        self.parameters.cooldown_end_ts = cooldown_ts if state == COMMON.EpexOMTState.RESTRICTED else None
        log.debug("Changed {} OMT end dates: Tolerance ends {}; Cooldown ends {}".format(
            self.parameters.limit_type,
            ts_to_isoformat(self.parameters.tolerance_end_ts),
            ts_to_isoformat(self.parameters.cooldown_end_ts)
        ))

    @only_initialized()
    def _update_recovery_omt_target(self):  # type: () -> None
        """Calculates and updates the omt_recovery_target"""
        self.parameters.recovery_target = self.parameters.lower_threshold


class ShortOMTManager(OMTManager):
    """OMTManager class for the short observation period"""

    def __init__(self, throttling_limit, change_handlers=None):  # type: (int, dict[str, any]|None) -> None
        super(ShortOMTManager, self).__init__(COMMON.RateLimitType.Epex.short, throttling_limit, change_handlers)


class LongOMTManager(OMTManager):
    """OMTManager class for the long observation period"""

    def __init__(self, throttling_limit, change_handlers=None):  # type: (int, dict[str, any]|None) -> None
        super(LongOMTManager, self).__init__(COMMON.RateLimitType.Epex.long, throttling_limit, change_handlers)

    @only_initialized()
    def _get_autotrader_state(self, current_time):  # type: (float) -> str|None
        """Evaluates the current state of OMT and returns the current state-string."""
        previous_bucket = self._current_bucket(current_time) - self._bucket_length
        previous_bucket_value = self._buckets[previous_bucket] if previous_bucket in self._buckets else 0
        # If the state is currently BLOCKING, the previous bucket must be empty, before aT can leave BLOCKING state.
        if previous_bucket_value != 0 and self.autotrader_state.current == COMMON.ThrottlingState.BLOCKING:
            return COMMON.ThrottlingState.BLOCKING

        # Otherwise evaluate normally:
        return super(LongOMTManager, self)._get_autotrader_state(current_time)

    @only_initialized()
    def _update_recovery_omt_target(self):  # type: () -> None
        """Calculates and sets the recovery_target."""
        self.parameters.recovery_target = self.throttling_threshold
